### ISSUE TITLE
Todo List 

### ISSUE THREAD

**Issue by TheGenocides** [TheGenocides/wilhelmina#5]
# Todo List

pls tolonging gua, sementara gua elkaes pls plspl :DD makasih gaisss

## Major

- [x]  Add footer (#4)
- [x] Competitions Page (#2)
- [x] Fix text issues
- [x] Decorate navbar

## Minor

- [x] Make cursor pointer when hovering the "ENLIST NOW" button 
- [x] Make sure text in Competition Card is a one liner text

![image](https://github.com/TheGenocides/wilhelmina/assets/82718066/dfe1480a-0fc8-4586-b769-9ec496a7547d)

**Comment by 2ndmurphy** [comment]
sudah di fix guys
